# Harmony Jekyll theme general configurations 

# Base URL
baseurl: 

# Site live URL
url: http://jnak.github.io

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Jnak
  # Little description about your site
  description: All things reacted.
  meta_description: All things reacted.
  basetheme: blue-water # pre defined thmes are darken, blue-water, redish, theme-base-01 
  author: # Author details
    name: Julien Nakache
    email: julien.nakache@gmail.com
    url: http://jnak.github.io

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: jnak
    twitter: juliennakache
    facebook: julien.nakache
    # gplus: +GayanVirajith
    # dribble: gayan
    # pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
